[pytest]
testpaths = tests
addopts = -v --html=Reports/reporte.html --self-contained-html
markers =
    ui: pruebas automatizadas de interfaz con Selenium WebDriver
    api: pruebas automatizadas de servicios REST con requests
log_cli = true
log_cli_level = INFO
log_file = logs/pytest.log
log_file_level = INFO
